# Constantes relacionadas con elecciones
# Si se agrega más ELECCIONES  tmb actualizar en tipo_acta.py
COD_ELEC_PRESIDENTE = '10'
COD_ELEC_CONGRESAL = '11'
COD_ELEC_PARLAMENTO = '12'
COD_ELEC_DIPUTADO = '13'
COD_ELEC_SENADO_MULTIPLE = '14'
COD_ELEC_SENADO_UNICO = '15'
COD_ELEC_REGIONAL = '01'
COD_ELEC_CONSEJERO = '02'
COD_ELEC_DISTRITAL = '04'
COD_ELEC_PROVINCIAL = '03'
COD_ELEC_REVOCATORIA = '07'

TIPO_HOJA_STAE_TRANSMITIDA_A4 = 1
TIPO_HOJA_STAE_NO_TRANSMITIDA_A4 = 2
TIPO_HOJA_CONTINGENCIA_A3 = 3

SOLUCION_TECNOLOGICA_STAE = 2
SOLUCION_TECNOLOGICA_CONVENCIONAL = 1

# Si se agrega más TIPOS  tmb actualizar en tipo_acta.py
ABREV_ACTA_ESCRUTINIO = 'AE'
ABREV_ACTA_ESCRUTINIO_HORIZONTAL = 'AEH'
ABREV_ACTA_INSTALACION_SUFRAGIO = 'AIS'

ABREV_ACTA_ESCRUTINIO_STAE = 'AES'
ABREV_ACTA_ESCRUTINIO_STAE_HORIZONTAL = 'AESH'
ABREV_ACTA_INSTALACION_STAE = 'AIE'
ABREV_ACTA_SUFRAGIO_STAE = 'ASE'

ABREV_ACTA_ESCRUTINIO_EXTRANJERO = 'AEE'
ABREV_ACTA_ESCRUTINIO_HORIZONTAL_EXTRANJERO = 'AEEH'
ABREV_ACTA_INSTALACION_SUFRAGIO_EXTRANJERO = 'AISE'

ABREV_HOJA_ASISTENCIA_MM = 'MM'
ABREV_RELACION_MM_NO_SORTEADOS = 'MMC'

ABREV_HOJA_ASISTENCIA_MM_STAE = 'MMS'
ABREV_RELACION_MM_NO_SORTEADOS_STAE = 'MMCS'
ABREV_HOJA_ASISTENCIA_MM_EXTRANJERO = 'MME'
ABREV_RELACION_MM_NO_SORTEADOS_EXTRANJERO = 'MMCE'

# Constantes para tipos de observación
OBS_MM = 'OBS_MM'
OBS_MMC = 'OBS_MMC'
LIST_MM = 'LIST_MM'
LIST_MMC = 'LIST_MMC'

NUMERO_FILAS_ANTES_DE_LINEAS_GUIAS = 20
THRESHOLD_CLUSTERING_DBSCAN = 65

INPUT_AREA = 90
INPUT_ALTURA = 15
INPUT_TRAZOS_ALTURA = 5

COPIA_A_COLOR = True
DEFAULT_TIMEOUT = 30

#Constantes colas
QUEUE_LOGGER_VALUE_VALIDATE = "VALIDATE"
QUEUE_LOGGER_VALUE_PROCESS = "PROCESS"
QUEUE_LOGGER_VALUE_MIEMBROS_MESA = "MIEMBROS_MESA"
QUEUE_LOGGER_VALUE_LISTA_ELECTORES = "LISTA_ELECTORES"
QUEUE_LOGGER_VALUE_STAE = "STAE"
#Constantes secciones de corte
ABREV_FIRMA = "sign"
ABREV_FIRMA_PERSONEROS = "sign_ae_pr"
ABREV_VOTO = "voto"
ABREV_TABLA_VOTO_TOTAL = "voto_ae"
ABREV_TABLA_VOTO_PREFERENCIAL = "voto_pre_ae"
ABREV_TOTAL_CIUDADANOS = "cvas_as_n"

ABREV_CONTROL_CALIDAD_TOTAL_VOTOS = "TOT_VOTOS"
ABREV_CONTROL_CALIDAD_TOTAL_VOTOS_PREFERENCIALES = "VOTO_PRE"

MENSAJE_VALIDACION_TABLA_VOTOS = "Fallo en la localizacion de la tabla de votos totales."
MENSAJE_VALIDACION_TABLA_PREFERENCIAL = "Fallo en la localizacion de la tabla de votos preferenciales."
MENSAJE_VALIDACION_TABLAS_AMBOS = "Fallo en la localizacion de ambas tablas"

ACTA_HEIGHT_DEFAULT = 5050

SECCION_OBSERVACION_ESCRUTINIO = 'OBS_AE'

FLUJO_EXTRANJERO = "extranjero"
FLUJO_STAE = "stae"
FLUJO_CONVENCIONAL = "convencional"