package pe.gob.onpe.sceorcbackend.model.enums;

public enum TransmisionNacionEnum {

    ACTA_PENDIENTE_TRANSMISION,

    DIGTAL_RECIBIDA_TRANSMISION,

    ACTA_APROBADA_TRANSMISION,
    ACTA_CELESTE_APROBADA_TRANSMISION,
    INITIAL_TRANSMISION,
    PRIMERA_TRANSMISION,
    SEGUNDA_TRANSMISION,
    ENVIADA_JEE_TRANSMISION,

    CARGONO_NOINSTAL_EXT_SINI_TRANSMISION,

    CARGO_INFUNDADA_TRANSMISION,
    DEVUELTA_JEE_TRANSMISION,
    CUARTA_TRANSMISION,

    ASOCIACION_RESOL_TRANSMISION,
    PRIMERA_VERI_TRANSMISION,
    A_SEGUNDA_VERI_TRANSMISION,
    SEGUNDA_VERI_TRANSMISION,
    PROC_NORMAL_VERI_TRANSMISION,
    PROC_OBS_VERI_TRANSMISION,
    PROC_POR_CORREGIR_VERI_TRANSMISION,
    RECHAZAR_EN_VERIFICACION_TRANSMISION,

    RECHAZAR_EN_DIGITALIZACION,
    VERIFICACION_TRANSMISION,
    APLICAR_RES_TRANSMISION,
    PUESTA_CERO,
    REPROCESO,
    REPROCESAMIENTO_ACTA,

    OMISOS_MIEMBRO_MESA,


    OMISOS_LISTA_ELECTORES_VOTANTES,

    REGISTRO_PERSONEROS,

    REGISTRO_MIEMBRO_MESA_ESCRUTINIO,
    
    CONTROL_CALIDAD_TRANSMISION,

    CC_RECHAZAR_RES_TRANSMISION,
    
    SOBRES_CELESTES,
}
