package pe.gob.onpe.sceorcbackend.utils;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import pe.gob.onpe.sceorcbackend.model.importar.dto.ImportarDto;

public class JsonUtils {

    private JsonUtils() {
    }

    public static ImportarDto emular() throws JsonProcessingException {


        ObjectMapper objectMapper = new ObjectMapper();


        String json = """
                  {
                  idCentroComputo: 1,
                  proceso: abc,
                  ambitoElectoral: [
                    {
                        id: 1,
                        idCentroComputo: 1001,
                        proceso: Proceso A,
                        idPadre: 10,
                        nombre: Ambito Electoral 1,
                        tipoAmbitoElectoral: 1,
                        activo: 1,
                        audUsuarioCreacion: Usuario1,
                        audFechaCreacion: 2022-05-01,
                        audUsuarioModificacion: Usuario2,
                        audFechaModificacion: 2022-05-15
                    },
                    {
                        id: 2,
                        idCentroComputo: 1002,
                        proceso: Proceso B,
                        idPadre: 20,
                        nombre: Ambito Electoral 2,
                        tipoAmbitoElectoral: 2,
                        activo: 1,
                        audUsuarioCreacion: Usuario3,
                        audFechaCreacion: 2022-06-01,
                        audUsuarioModificacion: Usuario4,
                        audFechaModificacion: 2022-06-15
                    }
                  ],
                  agrupacionPolitica: [
                  {
                    id: 1,
                    idCentroComputo: 1001,
                    proceso: Proceso A,
                    codigo: AP001,
                    descripcion: Agrupación Política 1,
                    tipoAgrupacionPolitica: 1,
                    estado: 1,
                    ubigeoMaximo: Lima,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  },
                  {
                    id: 2,
                    idCentroComputo: 1002,
                    proceso: Proceso B,
                    codigo: AP002,
                    descripcion: Agrupación Política 2,
                    tipoAgrupacionPolitica: 2,
                    estado: 1,
                    ubigeoMaximo: Arequipa,
                    activo: 1,
                    audUsuarioCreacion: Usuario3,
                    audFechaCreacion: 2022-06-01,
                    audUsuarioModificacion: Usuario4,
                    audFechaModificacion: 2022-06-15
                  }
                ],
                  archivo: [
                    {
                    idCentroComputo:1,
                    proceso:proceso a,
                    id: 1,
                    guid:xxxxx,
                    nombre: hola,
                    nombreOriginal:hola 1,
                    formato:xxx,
                    peso:2MB
                    },
                    {
                    idCentroComputo:1,
                    proceso:proceso b,
                    id: 1,
                    guid:aaaa,
                    nombre: aaaaa,
                    nombreOriginal:hola 1,
                    formato:xxx,
                    peso:2MB
                    },
                    {
                    idCentroComputo:1,
                    proceso:proceso a,
                    id: 1,
                    guid:xxxxx,
                    nombre: hola,
                    nombreOriginal:hola 1,
                    formato:xxx,
                    peso:2MB
                    },
                    {
                    idCentroComputo:1,
                    proceso:proceso b,
                    id: 1,
                    guid:aaaa,
                    nombre: aaaaa,
                    nombreOriginal:hola 1,
                    formato:xxx,
                    peso:2MB
                    }
                ],
                acta: [
                    {
                        idCentroComputo: 123,
                        proceso: Proceso ABC,
                        id: 456,
                        idMesa: 789,
                        idDetUbigeoEleccion: 987,
                        idArchivoEscrutinio: 654,
                        idArchivoInstalacionSufragio: 321,
                        numeroCopia: Copia 1,
                        numeroLote: Lote 123,
                        tipoLote: Tipo A,
                        electoresHabiles: 1000,
                        cvas: 800,
                        votosCalculados: 750,
                        totalVotos: 700,
                        estadoActa: Aprobada,
                        estadoCc: Activo,
                        estadoActaResolucion: Resuelta,
                        estadoDigitalizacion: Completa,
                        estadoErrorMaterial: No hay errores,
                        digitalizacionEscrutinio: 1,
                        digitalizacionInstalacionSufragio: 1,
                        controlDigEscrutinio: 1,
                        controlDigInstalacionSufragio: 1,
                        observDigEscrutinio: Observación escrutinio,
                        observDigInstalacionSufragio: Observación instalación sufragio,
                        digitacionHoras: 3,
                        digitacionVotos: 500,
                        digitacionObserv: 5,
                        digitacionFirmas: 3,
                        controlDigitacion: 1,
                        horaEscrutinioAutomatico: 08:00,
                        horaEscrutinioManual: 08:30,
                        horaInstalacionAutomatico: 07:00,
                        horaInstalacionManual: 07:30,
                        descripcionObservAutomatico: Descripción observación automático,
                        descripcionObservManual: Descripción observación manual,
                        escrutinioFirmaMm1Automatico: 2,
                        escrutinioFirmaMm1Manual: 3,
                        escrutinioFirmaMm2Automatico: 4,
                        escrutinioFirmaMm2Manual: 5,
                        escrutinioFirmaMm3Automatico: 6,
                        escrutinioFirmaMm3Manual: 7,
                        instalacionFirmaMm1Automatico: 1,
                        instalacionFirmaMm1Manual: 2,
                        instalacionFirmaMm2Automatico: 3,
                        instalacionFirmaMm2Manual: 4,
                        instalacionFirmaMm3Automatico: 5,
                        instalacionFirmaMm3Manual: 6,
                        sufragioFirmaMm1Automatico: 1,
                        sufragioFirmaMm1Manual: 2,
                        sufragioFirmaMm2Automatico: 3,
                        sufragioFirmaMm2Manual: 4,
                        sufragioFirmaMm3Automatico: 5,
                        sufragioFirmaMm3Manual: 6,
                        activo: 1,
                        audUsuarioCreacion: Usuario1,
                        audFechaCreacion: 2022-05
                    },
                    {
                        idCentroComputo: 789,
                        proceso: Proceso XYZ,
                        id: 123,
                        idMesa: 456,
                        idDetUbigeoEleccion: 654,
                        idArchivoEscrutinio: 987,
                        idArchivoInstalacionSufragio: 321,
                        numeroCopia: Copia 2,
                        numeroLote: Lote 456,
                        tipoLote: Tipo B,
                        electoresHabiles: 1500,
                        cvas: 1200,
                        votosCalculados: 1100,
                        totalVotos: 1000,
                        estadoActa: Pendiente,
                        estadoCc: Inactivo,
                        estadoActaResolucion: Sin resolver,
                        estadoDigitalizacion: Incompleta,
                        estadoErrorMaterial: Errores encontrados,
                        digitalizacionEscrutinio: 0,
                        digitalizacionInstalacionSufragio: 0,
                        controlDigEscrutinio: 0,
                        controlDigInstalacionSufragio: 0,
                        observDigEscrutinio: Sin observaciones,
                        observDigInstalacionSufragio: Sin observaciones,
                        digitacionHoras: 5,
                        digitacionVotos: 800,
                        digitacionObserv: 10,
                        digitacionFirmas: 5,
                        controlDigitacion: 0,
                        horaEscrutinioAutomatico: 09:00,
                        horaEscrutinioManual: 09:30,
                        horaInstalacionAutomatico: 08:00,
                        horaInstalacionManual: 08:30,
                        descripcionObservAutomatico: Descripción observación automático,
                        descripcionObservManual: Descripción observación manual,
                        escrutinioFirmaMm1Automatico: 1,
                        escrutinioFirmaMm1Manual: 2,
                        escrutinioFirmaMm2Automatico: 3,
                        escrutinioFirmaMm2Manual: 4,
                        escrutinioFirmaMm3Automatico: 5,
                        escrutinioFirmaMm3Manual: 6,
                        instalacionFirmaMm1Automatico: 1,
                        instalacionFirmaMm1Manual: 2,
                        instalacionFirmaMm2Automatico: 3,
                        instalacionFirmaMm2Manual: 4,
                        instalacionFirmaMm3Automatico: 5,
                        instalacionFirmaMm3Manual: 6,
                        sufragioFirmaMm1Automatico: 1,
                        sufragioFirmaMm1Manual: 2,
                        sufragioFirmaMm2Automatico: 3,
                        sufragioFirmaMm2Manual: 4,
                        sufragioFirmaMm3Automatico: 5,
                        sufragioFirmaMm3Manual: 6,
                        activo: 1,
                        audUsuarioCreacion: Usuario2,
                        audFechaCreacion: 2022-05
                    }
                ],
                actaHistorial: [
                    {
                        idCentroComputo: 123,
                        proceso: Proceso ABC,
                        id: 456,
                        correlativo:111,
                        idMesa: 789,
                        idDetUbigeoEleccion: 987,
                        idArchivoEscrutinio: 654,
                        idArchivoInstalacionSufragio: 321,
                        numeroCopia: Copia 1,
                        numeroLote: Lote 123,
                        tipoLote: Tipo A,
                        electoresHabiles: 1000,
                        cvas: 800,
                        votosCalculados: 750,
                        totalVotos: 700,
                        estadoActa: Aprobada,
                        estadoCc: Activo,
                        estadoActaResolucion: Resuelta,
                        estadoDigitalizacion: Completa,
                        estadoErrorMaterial: No hay errores,
                        digitalizacionEscrutinio: 1,
                        digitalizacionInstalacionSufragio: 1,
                        controlDigEscrutinio: 1,
                        controlDigInstalacionSufragio: 1,
                        observDigEscrutinio: Observación escrutinio,
                        observDigInstalacionSufragio: Observación instalación sufragio,
                        digitacionHoras: 3,
                        digitacionVotos: 500,
                        digitacionObserv: 5,
                        digitacionFirmas: 3,
                        controlDigitacion: 1,
                        horaEscrutinioAutomatico: 08:00,
                        horaEscrutinioManual: 08:30,
                        horaInstalacionAutomatico: 07:00,
                        horaInstalacionManual: 07:30,
                        descripcionObservAutomatico: Descripción observación automático,
                        descripcionObservManual: Descripción observación manual,
                        escrutinioFirmaMm1Automatico: 2,
                        escrutinioFirmaMm1Manual: 3,
                        escrutinioFirmaMm2Automatico: 4,
                        escrutinioFirmaMm2Manual: 5,
                        escrutinioFirmaMm3Automatico: 6,
                        escrutinioFirmaMm3Manual: 7,
                        instalacionFirmaMm1Automatico: 1,
                        instalacionFirmaMm1Manual: 2,
                        instalacionFirmaMm2Automatico: 3,
                        instalacionFirmaMm2Manual: 4,
                        instalacionFirmaMm3Automatico: 5,
                        instalacionFirmaMm3Manual: 6,
                        sufragioFirmaMm1Automatico: 1,
                        sufragioFirmaMm1Manual: 2,
                        sufragioFirmaMm2Automatico: 3,
                        sufragioFirmaMm2Manual: 4,
                        sufragioFirmaMm3Automatico: 5,
                        sufragioFirmaMm3Manual: 6,
                        activo: 1,
                        audUsuarioCreacion: Usuario1,
                        audFechaCreacion: 2022-05
                    },
                    {
                        idCentroComputo: 789,
                        proceso: Proceso XYZ,
                        id: 123,
                        correlativo:222,
                        idMesa: 456,
                        idDetUbigeoEleccion: 654,
                        idArchivoEscrutinio: 987,
                        idArchivoInstalacionSufragio: 321,
                        numeroCopia: Copia 2,
                        numeroLote: Lote 456,
                        tipoLote: Tipo B,
                        electoresHabiles: 1500,
                        cvas: 1200,
                        votosCalculados: 1100,
                        totalVotos: 1000,
                        estadoActa: Pendiente,
                        estadoCc: Inactivo,
                        estadoActaResolucion: Sin resolver,
                        estadoDigitalizacion: Incompleta,
                        estadoErrorMaterial: Errores encontrados,
                        digitalizacionEscrutinio: 0,
                        digitalizacionInstalacionSufragio: 0,
                        controlDigEscrutinio: 0,
                        controlDigInstalacionSufragio: 0,
                        observDigEscrutinio: Sin observaciones,
                        observDigInstalacionSufragio: Sin observaciones,
                        digitacionHoras: 5,
                        digitacionVotos: 800,
                        digitacionObserv: 10,
                        digitacionFirmas: 5,
                        controlDigitacion: 0,
                        horaEscrutinioAutomatico: 09:00,
                        horaEscrutinioManual: 09:30,
                        horaInstalacionAutomatico: 08:00,
                        horaInstalacionManual: 08:30,
                        descripcionObservAutomatico: Descripción observación automático,
                        descripcionObservManual: Descripción observación manual,
                        escrutinioFirmaMm1Automatico: 1,
                        escrutinioFirmaMm1Manual: 2,
                        escrutinioFirmaMm2Automatico: 3,
                        escrutinioFirmaMm2Manual: 4,
                        escrutinioFirmaMm3Automatico: 5,
                        escrutinioFirmaMm3Manual: 6,
                        instalacionFirmaMm1Automatico: 1,
                        instalacionFirmaMm1Manual: 2,
                        instalacionFirmaMm2Automatico: 3,
                        instalacionFirmaMm2Manual: 4,
                        instalacionFirmaMm3Automatico: 5,
                        instalacionFirmaMm3Manual: 6,
                        sufragioFirmaMm1Automatico: 1,
                        sufragioFirmaMm1Manual: 2,
                        sufragioFirmaMm2Automatico: 3,
                        sufragioFirmaMm2Manual: 4,
                        sufragioFirmaMm3Automatico: 5,
                        sufragioFirmaMm3Manual: 6,
                        activo: 1,
                        audUsuarioCreacion: Usuario2,
                        audFechaCreacion: 2022-05
                    }
                ],
                  detActa: [
                    {
                    idCentroComputo:1,
                    proceso:proceso a,
                    id: 1,
                    idCabActa:1,
                    idAgrupacionPolitica: 1,
                    posicion:1,
                    votos: 222,
                    estadoErrorMaterial:error,
                    ilegible: malo
                    },
                    {
                    idCentroComputo:1,
                    proceso:proceso a,
                    id: 2,
                    idCabActa:1,
                    idAgrupacionPolitica: 1,
                    posicion:1,
                    votos: 222,
                    estadoErrorMaterial:error,
                    ilegible: malo
                    }
                ],
                  detActaHistorial: [
                    {
                        id: 123,
                        correlativo: 456,
                        idCentroComputo: 789,
                        proceso: Proceso ABC,
                        idCabActa: 101,
                        idAgrupacionPolitica: 102,
                        posicion: 1,
                        votos: 100,
                        estadoErrorMaterial: Error,
                        ilegible: No,
                        activo: 1,
                        audUsuarioCreacion: Usuario1,
                        audFechaCreacion: 2022-05-01,
                        audUsuarioModificacion: Usuario2,
                        audFechaModificacion: 2022-05-15
                    },
                    {
                        id: 124,
                        correlativo: 456,
                        idCentroComputo: 789,
                        proceso: Proceso ABC,
                        idCabActa: 101,
                        idAgrupacionPolitica: 102,
                        posicion: 1,
                        votos: 100,
                        estadoErrorMaterial: Error,
                        ilegible: No,
                        activo: 1,
                        audUsuarioCreacion: Usuario1,
                        audFechaCreacion: 2022-05-01,
                        audUsuarioModificacion: Usuario2,
                        audFechaModificacion: 2022-05-15
                    }
                ],
                  catalogoEstructura: [
                  {
                    id: 1,
                    idCentroComputo: 1001,
                    proceso: Proceso A,
                    idCatalogo: 10,
                    columna: Columna A,
                    nombre: Nombre A,
                    numCodigo: 100,
                    codigo: Código A,
                    orden: 1,
                    tipo: Tipo A,
                    informacionAdicional: Información adicional A,
                    obligatorio: 1,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  },
                  {
                    id: 2,
                    idCentroComputo: 1002,
                    proceso: Proceso B,
                    idCatalogo: 20,
                    columna: Columna B,
                    nombre: Nombre B,
                    numCodigo: 200,
                    codigo: Código B,
                    orden: 2,
                    tipo: Tipo B,
                    informacionAdicional: Información adicional B,
                    obligatorio: 0,
                    activo: 1,
                    audUsuarioCreacion: Usuario3,
                    audFechaCreacion: 2022-06-01,
                    audUsuarioModificacion: Usuario4,
                    audFechaModificacion: 2022-06-15
                  }
                ],
                  catalogoReferencia: [
                  {
                    id: 1,
                    idCentroComputo: 1001,
                    proceso: Proceso A,
                    idCatalogo: 10,
                    tablaReferencia: Tabla de referencia A,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  },
                  {
                    id: 2,
                    idCentroComputo: 1002,
                    proceso: Proceso B,
                    idCatalogo: 20,
                    tablaReferencia: Tabla de referencia B,
                    activo: 1,
                    audUsuarioCreacion: Usuario3,
                    audFechaCreacion: 2022-06-01,
                    audUsuarioModificacion: Usuario4,
                    audFechaModificacion: 2022-06-15
                  },
                  {
                    id: 3,
                    idCentroComputo: 1003,
                    proceso: Proceso C,
                    idCatalogo: 30,
                    tablaReferencia: Tabla de referencia C,
                    activo: 1,
                    audUsuarioCreacion: Usuario5,
                    audFechaCreacion: 2022-07-01,
                    audUsuarioModificacion: Usuario6,
                    audFechaModificacion: 2022-07-15
                  }
                ],
                  ubigeoEleccionAgrupacionPolitica: [
                  {
                    id: 1,
                    idCentroComputo: 1001,
                    proceso: Proceso A,
                    idDetUbigeoEleccion: 10,
                    idAgrupacionPolitica: 20,
                    posicion: 1,
                    estado: 1,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  },
                  {
                    id: 2,
                    idCentroComputo: 1002,
                    proceso: Proceso B,
                    idDetUbigeoEleccion: 20,
                    idAgrupacionPolitica: 30,
                    posicion: 2,
                    estado: 1,
                    activo: 1,
                    audUsuarioCreacion: Usuario3,
                    audFechaCreacion: 2022-06-01,
                    audUsuarioModificacion: Usuario4,
                    audFechaModificacion: 2022-06-15
                  },
                  {
                    id: 3,
                    idCentroComputo: 1003,
                    proceso: Proceso C,
                    idDetUbigeoEleccion: 30,
                    idAgrupacionPolitica: 40,
                    posicion: 3,
                    estado: 1,
                    activo: 1,
                    audUsuarioCreacion: Usuario5,
                    audFechaCreacion: 2022-07-01,
                    audUsuarioModificacion: Usuario6,
                    audFechaModificacion: 2022-07-15
                  }
                ],
                  eleccion: [],
                  localVotacion: [],
                  mesa: [
                  {
                    id: 1,
                    idCentroComputo: 10,
                    proceso: Proceso A,
                    idLocalVotacion: 100,
                    mesa: Mesa 1,
                    cantidadElectoresHabiles: 200,
                    cantidadElectoresHabilesExtranjeros: 20,
                    discapacidad: 0,
                    solucionTecnologica: 1,
                    estadoMesa: Abierta,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  },
                  {
                    id: 2,
                    idCentroComputo: 20,
                    proceso: Proceso B,
                    idLocalVotacion: 200,
                    mesa: Mesa 2,
                    cantidadElectoresHabiles: 150,
                    cantidadElectoresHabilesExtranjeros: 15,
                    discapacidad: 1,
                    solucionTecnologica: 0,
                    estadoMesa: Cerrada,
                    activo: 1,
                    audUsuarioCreacion: Usuario3,
                    audFechaCreacion: 2022-06-01,
                    audUsuarioModificacion: Usuario4,
                    audFechaModificacion: 2022-06-15
                  }
                ],
                  procesoElectoral: [],
                  transmisionEnvio: [
                  {
                    id: 1,
                    idCentroComputo: 10,
                    proceso: Proceso A,
                    tramaDato: Trama de datos 1,
                    tramaImagen: Trama de imagen 1,
                    estado: 1,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  },
                  {
                    id: 2,
                    idCentroComputo: 20,
                    proceso: Proceso B,
                    tramaDato: Trama de datos 2,
                    tramaImagen: Trama de imagen 2,
                    estado: 0,
                    activo: 1,
                    audUsuarioCreacion: Usuario3,
                    audFechaCreacion: 2022-06-01,
                    audUsuarioModificacion: Usuario4,
                    audFechaModificacion: 2022-06-15
                  }
                ],
                  transmisionRecepcion: [
                  {
                    id: 1,
                    proceso: Proceso A,
                    idCentroComputo: 10,
                    tramaDato: Trama de datos 1,
                    tramaImagen: Trama de imagen 1,
                    estado: 1,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  },
                  {
                    id: 2,
                    proceso: Proceso B,
                    idCentroComputo: 20,
                    tramaDato: Trama de datos 2,
                    tramaImagen: Trama de imagen 2,
                    estado: 0,
                    activo: 1,
                    audUsuarioCreacion: Usuario3,
                    audFechaCreacion: 2022-06-01,
                    audUsuarioModificacion: Usuario4,
                    audFechaModificacion: 2022-06-15
                  }
                ],
                  ubigeo: [],
                  ubigeoEleccion: [
                  {
                    id: 1,
                    idCentroComputo: 1001,
                    proceso: Proceso A,
                    idUbigeo: 10,
                    idEleccion: 20,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  },
                  {
                    id: 2,
                    idCentroComputo: 1002,
                    proceso: Proceso B,
                    idUbigeo: 20,
                    idEleccion: 30,
                    activo: 1,
                    audUsuarioCreacion: Usuario3,
                    audFechaCreacion: 2022-06-01,
                    audUsuarioModificacion: Usuario4,
                    audFechaModificacion: 2022-06-15
                  },
                  {
                    id: 3,
                    idCentroComputo: 1003,
                    proceso: Proceso C,
                    idUbigeo: 30,
                    idEleccion: 40,
                    activo: 1,
                    audUsuarioCreacion: Usuario5,
                    audFechaCreacion: 2022-07-01,
                    audUsuarioModificacion: Usuario6,
                    audFechaModificacion: 2022-07-15
                  }
                ],
                  centroComputo: [
                  {
                    id: 1,
                    proceso: Proceso A,
                    idPadre: 10,
                    nombre: Centro de Cómputo 1,
                    activo: 1,
                    audUsuarioCreacion: Usuario1,
                    audFechaCreacion: 2022-05-01,
                    audUsuarioModificacion: Usuario2,
                    audFechaModificacion: 2022-05-15
                  }
                ]
                }
                """;


        return objectMapper.readValue(json, ImportarDto.class);


    }

}
